name: Trigger auto deployment for test-infra

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-infra-AutoDeployTrigger-f3f098be-33b2-4c6e-9f8f-08f1f3cb04fe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTINFRA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTINFRA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTINFRA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: testnfraxxx.azurecr.io
          registryUsername: ${{ secrets.TESTINFRA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTINFRA_REGISTRY_PASSWORD }}
          containerAppName: test-infra
          resourceGroup: ex-INT-AOAIS-POC
          imageToBuild: testnfraxxx.azurecr.io/test-infra:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


