jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: DNS Check
        run: |
          nslookup rddx-func-user4.azurewebsites.net
          nslookup rddx-func-user4.scm.azurewebsites.net

      - name: Connectivity Check
        run: |
          curl -I https://rddx-func-user4.scm.azurewebsites.net
