name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTINFRA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTINFRA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTINFRA_AZURE_SUBSCRIPTION_ID }}

      - name: Build Image in ACR
        run: |
          az acr build \
            --registry testinfraxxx \
            --image test-infra:${{ github.sha }} \
            .

      - name: Deploy ACA
        run: |
          az containerapp update \
            --name test-infra \
            --resource-group ex-INT-AOAIS-POC \
            --image testinfraxxx.azurecr.io/test-infra:${{ github.sha }}
